# Generated by Django 4.1 on 2022-11-25 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of the Member', max_length=150, verbose_name='Member Name')),
                ('designation', models.CharField(default='', help_text='Designation/Title of the member', max_length=250, verbose_name='Member Designation')),
                ('affiliation', models.TextField(help_text='Affiliation of the Team Member', verbose_name='Member Affiliation')),
                ('email', models.CharField(default='', help_text='e-Mail address of the team member', max_length=150, verbose_name='Member e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Title of the News Article', max_length=300, verbose_name='Title of Article')),
                ('slug', models.SlugField(help_text='Article slug', max_length=200, unique=True, verbose_name='Slug')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Article updated on date', verbose_name='Updated on')),
                ('content', models.TextField(help_text='Content of the article', verbose_name='Article Content')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Article creation date', verbose_name='Created on')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(help_text='Article authored by this user', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Article Authored')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
