# Generated by Django 4.1 on 2022-12-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medulloblastoma_1_gse62600_metadata',
            name='groupI',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Disease')], null=True),
        ),
    ]
