# Generated by Django 4.1 on 2022-12-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtm', '0002_alter_medulloblastoma_1_gse62600_metadata_groupi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medulloblastoma_1_gse62600_metadata',
            name='groupI',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Disease')], default=None),
            preserve_default=False,
        ),
    ]
