# Generated by Django 4.1 on 2022-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meningioma_1_PXD007073',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinId', models.CharField(default='', help_text='UniProt Protein ID', max_length=200, verbose_name='Protein ID')),
                ('S1', models.FloatField()),
                ('S2', models.FloatField()),
                ('S3', models.FloatField()),
                ('S4', models.FloatField()),
                ('S5', models.FloatField()),
                ('S6', models.FloatField()),
                ('S7', models.FloatField()),
                ('S8', models.FloatField()),
                ('S9', models.FloatField()),
                ('S10', models.FloatField()),
                ('S11', models.FloatField()),
                ('S12', models.FloatField()),
                ('S13', models.FloatField()),
                ('S14', models.FloatField()),
                ('S15', models.FloatField()),
                ('S16', models.FloatField()),
                ('S17', models.FloatField()),
                ('S18', models.FloatField()),
                ('S19', models.FloatField()),
                ('S20', models.FloatField()),
                ('S21', models.FloatField()),
                ('S22', models.FloatField()),
                ('S23', models.FloatField()),
                ('S24', models.FloatField()),
                ('S25', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meningioma_1_PXD007073_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.TextField(help_text='Name of Source File', verbose_name='Source Name')),
                ('sampleId', models.CharField(help_text='The Sample ID', max_length=50, verbose_name='Sample ID')),
                ('sampleName', models.TextField(help_text='Name of Sample', verbose_name='Sample Name')),
                ('gender', models.IntegerField(choices=[('0', 'Male'), ('1', 'Female')], null=True)),
                ('age', models.IntegerField(help_text='Age of Patient', null=True, verbose_name='Age')),
                ('groupI', models.IntegerField(choices=[('0', 'Control'), ('1', 'Disease')])),
                ('groupII', models.IntegerField(choices=[('0', 'Control'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3')])),
                ('groupIII', models.IntegerField(choices=[(0, 'Anaplastic'), (1, 'Atypical'), (2, 'Fibroplastic'), (3, 'Meningothelial'), (4, 'Transitional')], null=True)),
                ('groupIV', models.IntegerField(choices=[(0, 'Brain Stem'), (1, 'Frontal'), (2, 'Lateral posterior fossa'), (3, 'Occipital'), (4, 'Olfactory groove'), (5, 'Parafalcine'), (6, 'Parasagittal'), (7, 'Parietal'), (8, 'Sphenoid wing')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meningioma_2_PXD014852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinId', models.CharField(default='', help_text='UniProt Protein ID', max_length=200, verbose_name='Protein ID')),
                ('S1', models.FloatField()),
                ('S2', models.FloatField()),
                ('S3', models.FloatField()),
                ('S4', models.FloatField()),
                ('S5', models.FloatField()),
                ('S6', models.FloatField()),
                ('S7', models.FloatField()),
                ('S8', models.FloatField()),
                ('S9', models.FloatField()),
                ('S10', models.FloatField()),
                ('S11', models.FloatField()),
                ('S12', models.FloatField()),
                ('S13', models.FloatField()),
                ('S14', models.FloatField()),
                ('S15', models.FloatField()),
                ('S16', models.FloatField()),
                ('S17', models.FloatField()),
                ('S18', models.FloatField()),
                ('S19', models.FloatField()),
                ('S20', models.FloatField()),
                ('S21', models.FloatField()),
                ('S22', models.FloatField()),
                ('S23', models.FloatField()),
                ('S24', models.FloatField()),
                ('S25', models.FloatField()),
                ('S26', models.FloatField()),
                ('S27', models.FloatField()),
                ('S28', models.FloatField()),
                ('S29', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meningioma_2_PXD014852_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.TextField(help_text='Name of Source File', verbose_name='Source Name')),
                ('sampleId', models.CharField(help_text='The Sample ID', max_length=50, verbose_name='Sample ID')),
                ('sampleName', models.TextField(help_text='Name of Sample', verbose_name='Sample Name')),
                ('gender', models.IntegerField(choices=[('0', 'Male'), ('1', 'Female')], null=True)),
                ('age', models.IntegerField(help_text='Age of Patient', null=True, verbose_name='Age')),
                ('groupI', models.IntegerField(choices=[('0', 'Control'), ('1', 'Disease')])),
                ('groupII', models.IntegerField(choices=[('0', 'Control'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3')])),
            ],
        ),
    ]
