# Generated by Django 4.1 on 2022-12-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0002_meningioma_3_pxd012923_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meningioma_1_pxd007073_metadata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='meningioma_1_pxd007073_metadata',
            name='groupI',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Disease')]),
        ),
        migrations.AlterField(
            model_name='meningioma_1_pxd007073_metadata',
            name='groupII',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3')]),
        ),
        migrations.AlterField(
            model_name='meningioma_2_pxd014852_metadata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='meningioma_2_pxd014852_metadata',
            name='groupI',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Disease')]),
        ),
        migrations.AlterField(
            model_name='meningioma_2_pxd014852_metadata',
            name='groupII',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3')]),
        ),
        migrations.AlterField(
            model_name='meningioma_3_pxd012923_metadata',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='meningioma_3_pxd012923_metadata',
            name='groupI',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Disease')], null=True),
        ),
    ]
