# Generated by Django 4.1 on 2023-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField(default='', help_text='Name of the Disease', max_length=500, verbose_name='Disease Name')),
                ('diseaseSlug', models.SlugField(help_text='Disease slug', max_length=500, unique=True, verbose_name='Slug')),
                ('DisGeNetDiseaseId', models.CharField(default='', help_text='DisGeNet Disease ID', max_length=100, verbose_name='DisGeNet Disease ID')),
                ('numGeneDisGeNet', models.PositiveIntegerField(help_text='Number of Genes (DisGeNet)', verbose_name='No. of Genes (DisGeNet)')),
                ('numGeneHarmonizome', models.PositiveIntegerField(help_text='Number of Genes (Harmonizome)', verbose_name='No. of Genes (Harmonizome)')),
            ],
        ),
    ]
