# Generated by Django 4.1 on 2023-01-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='diseaseSlug',
        ),
    ]
