# Generated by Django 4.1 on 2023-01-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbda', '0003_disease_harmonizomequeryterm_disease_includeinbddf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='DisGeNetDiseaseId',
            new_name='DisGeNETDiseaseId',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='numGeneDisGeNet',
            new_name='numGeneDisGeNET',
        ),
    ]
