# Generated by Django 4.1.3 on 2023-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbda', '0004_rename_disgenetdiseaseid_disease_disgenetdiseaseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='DisGeNETDiseaseId',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='HarmonizomeQueryTerm',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='includeInBDDF',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='numGeneDisGeNET',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='numGeneHarmonizome',
        ),
        migrations.AddField(
            model_name='disease',
            name='GARD',
            field=models.CharField(default='', help_text='GARD', max_length=100, null=True, verbose_name='GARD'),
        ),
        migrations.AddField(
            model_name='disease',
            name='HPO',
            field=models.CharField(default='', help_text='HPO', max_length=100, null=True, verbose_name='HPO'),
        ),
        migrations.AddField(
            model_name='disease',
            name='KEGG',
            field=models.CharField(default='', help_text='KEGG', max_length=100, null=True, verbose_name='KEGG'),
        ),
        migrations.AddField(
            model_name='disease',
            name='MESHID',
            field=models.CharField(default='', help_text='MESH ID', max_length=100, verbose_name='MESH ID'),
        ),
        migrations.AddField(
            model_name='disease',
            name='MedGenUID',
            field=models.CharField(default='', help_text='MedGen UID', max_length=100, null=True, verbose_name='MedGen UID'),
        ),
        migrations.AddField(
            model_name='disease',
            name='NCI',
            field=models.CharField(default='', help_text='NCI', max_length=100, null=True, verbose_name='NCI'),
        ),
        migrations.AddField(
            model_name='disease',
            name='OMIM',
            field=models.CharField(default='', help_text='OMIM', max_length=100, null=True, verbose_name='OMIM'),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.CharField(default='', help_text='Disease Description', max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='disease',
            name='diseaseOntology',
            field=models.CharField(default='', help_text='Disease Ontology', max_length=100, null=True, verbose_name='Disease Ontology'),
        ),
        migrations.AddField(
            model_name='disease',
            name='monarchInitiative',
            field=models.CharField(default='', help_text='Monarch Initiative', max_length=100, null=True, verbose_name='Monarch Initiative'),
        ),
        migrations.AddField(
            model_name='disease',
            name='orphanet',
            field=models.CharField(default='', help_text='Orphanet', max_length=100, null=True, verbose_name='Orphanet'),
        ),
        migrations.AddField(
            model_name='disease',
            name='umlsId',
            field=models.CharField(default='', help_text='UMLS', max_length=100, null=True, verbose_name='UMLS'),
        ),
    ]
