# Generated by Django 4.1 on 2022-12-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alzheimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Amyotrophic_Lateral_Sclerosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Frontotemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Glioblastoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Glioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Huntington',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medulloblastoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meningioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiple_Sclerosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parkinson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pituitary_Adenoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(default='', help_text='Gene Name', max_length=200, verbose_name='Gene Name')),
                ('DISGENET_Score', models.FloatField()),
                ('Pubpular_Score', models.FloatField()),
                ('Harmonizome_Score', models.FloatField()),
                ('Bionda_Score', models.FloatField()),
            ],
        ),
    ]
