# Generated by Django 4.1.3 on 2023-05-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmc', '0005_rename_edager_marker_d000067877_edgar_marker_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='D002546',
            new_name='D002545',
        ),
    ]
