# Generated by Django 4.1.3 on 2023-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d000544',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d000544',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d000690',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d000690',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d005909',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d005909',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d005910',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d005910',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d006816',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d006816',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d008527',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d008527',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d008579',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d008579',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d009103',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d009103',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d010300',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d010300',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d049912',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d049912',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
        migrations.AlterField(
            model_name='d057174',
            name='Drug_Name',
            field=models.CharField(default='', help_text='Drug Name', max_length=2000, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d057174',
            name='Smiles',
            field=models.CharField(default='', help_text='Smiles', max_length=2000, verbose_name='Smiles'),
        ),
    ]
