# Generated by Django 4.1.3 on 2023-05-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0002_alter_d000544_drug_name_alter_d000544_smiles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stitch_Part2',
        ),
        migrations.DeleteModel(
            name='Stitch_Part3',
        ),
        migrations.DeleteModel(
            name='Stitch_Part4',
        ),
    ]
