# Generated by Django 4.1.3 on 2023-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0003_delete_stitch_part2_delete_stitch_part3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDDF_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField(default='', help_text='Name of the Disease', max_length=500, verbose_name='Disease Name')),
                ('MESHID', models.CharField(default='', help_text='MESH ID', max_length=100, verbose_name='MESH ID')),
            ],
        ),
    ]
