# Generated by Django 4.1.3 on 2023-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0004_bddf_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='d000544',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d000690',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d005909',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d005910',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d006816',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d008527',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d008579',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d009103',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d010300',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d049912',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AddField(
            model_name='d057174',
            name='pref_name',
            field=models.CharField(default='', help_text='Drug Name', max_length=200, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='d000544',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d000690',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d005909',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d005910',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d006816',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d008527',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d008579',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d009103',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d010300',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d049912',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
        migrations.AlterField(
            model_name='d057174',
            name='Drug_Name',
            field=models.CharField(default='', help_text='IUPAC Name', max_length=2000, verbose_name='IUPAC Name'),
        ),
    ]
