# Generated by Django 4.1.3 on 2023-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0006_rename_stitch_part1_stitch_remove_d000544_pref_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chembl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chembl_ID', models.CharField(default='', help_text='Chembl ID', max_length=50, verbose_name='Chembl ID')),
                ('UniprotID', models.CharField(default='', help_text='Uniprot ID', max_length=200, verbose_name='Uniprot ID')),
                ('Smiles_ID', models.CharField(default='', help_text='Smiles ID', max_length=2000, verbose_name='Smiles ID')),
                ('Investigation', models.CharField(default='', help_text='Investigation', max_length=100, verbose_name='Investigation')),
                ('MOA', models.CharField(default='', help_text='TTD MOA', max_length=200, verbose_name='TTD MOA')),
                ('Toxicity', models.CharField(default='', help_text='Toxicity', max_length=500, verbose_name='Toxicity')),
                ('pIC50', models.FloatField(null=True)),
                ('Clue_MOA', models.CharField(default='', help_text='Clue MOA', max_length=200, verbose_name='Clue MOA')),
                ('Clinical_Phase', models.CharField(default='', help_text='Clinical Phase', max_length=200, verbose_name='Clinical Phase')),
            ],
        ),
        migrations.AlterField(
            model_name='stitch',
            name='Combined_Score',
            field=models.FloatField(help_text='Combined Score', null=True, verbose_name='Combined Score'),
        ),
    ]
