# Generated by Django 4.1.3 on 2023-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0007_chembl_alter_stitch_combined_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Names_Smiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug_Name', models.CharField(default='', help_text='Drug Name', max_length=100, verbose_name='Drug Name')),
                ('CNS', models.CharField(default='', help_text='CNS Drug', max_length=5, verbose_name='CNS Drug')),
                ('Smiles_ID', models.CharField(default='', help_text='Smiles ID', max_length=2000, verbose_name='Smiles ID')),
            ],
        ),
    ]
