# Generated by Django 4.1.3 on 2023-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddf', '0008_drug_names_smiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='d000544',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d000544',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d000690',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d000690',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d005909',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d005909',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d005910',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d005910',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d006816',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d006816',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d008527',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d008527',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d008579',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d008579',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d009103',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d009103',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d010300',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d010300',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d049912',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d049912',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
        migrations.AddField(
            model_name='d057174',
            name='Gene_Name',
            field=models.CharField(default='', help_text='Gene Name', max_length=300, verbose_name='Gene Name'),
        ),
        migrations.AddField(
            model_name='d057174',
            name='pref_name',
            field=models.CharField(default='', help_text='pref_name', max_length=300, verbose_name='pref_name'),
        ),
    ]
